name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # workflow_dispatch:

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: 10.x

      - name: package Install
        run: npm install

      - name: create dist
        run: npm run create-package

      - name: lambda deploy
        uses: actions/aws/cli@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        with:
          args: s3 sync app.zip/ s3://wedding-photo-api/lambda-edge-image-convert/ --delete
