name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # workflow_dispatch:

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: 10.x

      - name: package Install
        run: npm install

      - name: create dist
        run: npm run build

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # - uses: actions/aws/cli@master
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      #   with:
      #     args: s3 sync dist/ s3://[作成したバケット名] --delete
